name: "news"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2025-03-09"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "./log/news.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: "mysql8019"
  port: 3306
  user: "root"
  password: "root"
  dbname: "news"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "redis507"
  port: 6379
  db: 0
  pool_size: 100