name: Build & Push news to Docker Hub

on:
  push:
    branches:
      - main  # Trigger when pushing to the main branch
  pull_request:
    types:
      - closed  # Trigger when a PR is merged
    branches:
      - main    # Only trigger when the PR is merged into the main branch

env:
  IMAGE_NAME: news  # Image name
  DOCKERHUB_USERNAME: goatdjokovic

jobs:
  build-and-push:
    if: |
      github.event.pull_request.merged == true || github.event_name == 'push'  # Only run when a PR is merged or a push to main happens
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 3️⃣ Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest -f Dockerfile .

      # 4️⃣ Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
